### ISSUE TITLE
1.1.0 changelog and 1.0.0 have multiple duplicated lines, is it normal ?

### ISSUE THREAD

**Issue by clakech** [btford/grunt-conventional-changelog#31]

**Comment by eddiemonge** [comment]
Im not seeing this bug. If its still happening please let us know.

**Comment by oric01** [comment]
I encountered this bug once again but i finally found why.

I recently changed our branch model based on this one http://nvie.com/posts/a-successful-git-branching-model/ 

In this model you create your tag based on the last `release` merge automatic commit (merge --no-ff) onto `master`.

You also merge your `release` onto `develop` branch and get another new commit.

Even in `develop` you can list any tags around __but__ since a tag is based on 1 commit, the last tag commit created from `master` does not exist in `develop` (because you never merge `master` in `develop`). 

In this conditions, `grunt-conventional-changelog` was considering the last tag based on `master` in our previous branch model (before we change our branch model) and then added previous commit in addition to latest commit.

Now, we create the release tag in the release branch (when the release is ready) and when we merge the `release` in `develop` we get the "tag" commit in develop and changelog works fine.

I hope this is clear enough and will help...
